/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASM_TT_GUI;

import ASM_TT_BLL.BLLCombobox;
import ASM_TT_BLL.BLLDangNhap;
import ASM_TT_BLL.BLLHoaDon;
import ASM_TT_DAL.DALChiTietHoDon;
import ASM_TT_BLL.BLLNhanVien;
import ASM_TT_DAL.DALHoaDon;
import ASM_TT_DTO.CTHD;
import ASM_TT_DTO.HoaDon;
import ASM_TT_DTO.NhanVien;
import ASM_TT_DTO.SanPham;
import ASM_TT_HALPER.ChuyenDoi;
import ASM_TT_HALPER.ThongBao;
import ASM_TT_HALPER.displayvalueModel;




import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author LENOVO
 */
public class TabHoaDon extends javax.swing.JPanel {

    public static String sql = "SELECT * FROM HoaDon";

    /**
     * Creates new form TabHoaDon
     */
    public TabHoaDon() {
        initComponents();
        BLLHoaDon.LoadHoaDon(tblHoaDon);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtMaKhachHang.setBackground(new Color(0, 0, 0, 0));
        txtMaNhanVien.setBackground(new Color(0, 0, 0, 0));
        txtGia.setBackground(new Color(0, 0, 0, 0));
        txtGhiChu.setBackground(new Color(0, 0, 0, 0));

        txtMaSanPham_ChiTietHoaDon.setBackground(new Color(0, 0, 0, 0));
        txtSoLuong_ChiTietHoaDon.setBackground(new Color(0, 0, 0, 0));
        txtGhiChu_ChiTietHoaDon.setBackground(new Color(0, 0, 0, 0));

    }

    public void LayDuLieuHoaDon() {
        String cautruyvan = "";
        cautruyvan = "select SoHoaDon,KhachHang.HoTen as TenKhachHang,NhanVien.HoTen,Gia,HoaDon.GhiChu "
                + "FROM HoaDon,KhachHang,NhanVien where HoaDon.MaKhachHang =KhachHang.MaKhachHang "
                + "and HoaDon.MaNhanVien=NhanVien.MaNhanVien  ";
        ResultSet rs = DALHoaDon.getALLHoaDon();
        DefaultTableModel tbModel = (DefaultTableModel) tblChiTietHoaDon.getModel();
        tbModel.setRowCount(0); // sét số dòng trong bảng về 0
        // Lấy dự liệu danh sách nhân viên từ DAL
        tblHoaDon.setModel(tbModel);
        int c = 0;
        try {
            while (rs.next()) {
                Object[] item = new Object[7];
                c++;
                item[0] = c;
                item[1] = rs.getInt("SoHoaDon");
                item[2] = ChuyenDoi.LayNgayString(rs.getDate("NgayNhapHoaDon"));
                item[3] = rs.getString("MaKhachHang");
                item[4] = rs.getString("MaNhanVien");
                item[5] = rs.getInt("Gia");
                item[6] = rs.getString("GhiChu");
                tbModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    public void LayDuLieuChiTietHoaDon(String SoHoaDon) {
        String cautruyvan = "";
        cautruyvan = " SELECT SoHoaDon,SoHoaDon,SanPham.TenSanPham,SoLuong,Gia,ChiTietHoaDon.GhiChu"
                + "FROM ChiTietHoaDon,SanPham where ChiTietHoaDon.MaSanPham=SanPham.MaSanPham  and SoHoaDon = " + SoHoaDon;
        ResultSet rs = DALChiTietHoDon.getALLCTHD();
        DefaultTableModel tbModel = (DefaultTableModel) tblChiTietHoaDon.getModel();
        tbModel.setRowCount(0); // sét số dòng trong bảng về 0
        // Lấy dự liệu danh sách nhân viên từ DAL
        tblChiTietHoaDon.setModel(tbModel);
        int c = 0;
        try {
            while (rs.next()) {
                c++;
                Object[] item = new Object[5];
                item[0] = c;
                item[1] = rs.getInt("SoHoaDon");
                item[2] = rs.getString("MaSanPham");
                item[3] = rs.getString("SoLuong");
                item[4] = rs.getString("GhiChu");
                tbModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        lblMaHoaDon_HoaDon = new javax.swing.JLabel();
        lblTongTien_HoaDon = new javax.swing.JLabel();
        lblNgayNhapHoaDon = new javax.swing.JLabel();
        lblMaKhachHang = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        btnThem_HoaDon = new javax.swing.JButton();
        btnSua_HoaDon = new javax.swing.JButton();
        btnReset_HoaDon = new javax.swing.JButton();
        lblMaNhanVien = new javax.swing.JLabel();
        txtNgayLapHD = new com.toedter.calendar.JDateChooser();
        txtGhiChu = new javax.swing.JTextField();
        txtMaKhachHang = new javax.swing.JTextField();
        lblSoHD = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        lblMaCTPM = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtMaSanPham_ChiTietHoaDon = new javax.swing.JTextField();
        txtSoLuong_ChiTietHoaDon = new javax.swing.JTextField();
        txtGhiChu_ChiTietHoaDon = new javax.swing.JTextField();
        lblSCTH_ChiTietHoaDon = new javax.swing.JLabel();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 204));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Hoá Đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel1.setOpaque(false);

        tblChiTietHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Số HĐ", "Mã Sản Phẩm", "Số Lượng", "Ghi Chú"
            }
        ));
        tblChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblChiTietHoaDon);
        if (tblChiTietHoaDon.getColumnModel().getColumnCount() > 0) {
            tblChiTietHoaDon.getColumnModel().getColumn(0).setMinWidth(40);
            tblChiTietHoaDon.getColumnModel().getColumn(0).setMaxWidth(40);
            tblChiTietHoaDon.getColumnModel().getColumn(1).setMaxWidth(40);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá Đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel2.setOpaque(false);

        tblHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Số  HĐ", "Ngày Nhập Hoá Đơn", "Mã  Khách Hàng", "Mã Nhân Viên", "Giá", "Ghi Chú"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoaDon);
        if (tblHoaDon.getColumnModel().getColumnCount() > 0) {
            tblHoaDon.getColumnModel().getColumn(0).setMaxWidth(40);
            tblHoaDon.getColumnModel().getColumn(1).setMaxWidth(40);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel14.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá Đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel14.setOpaque(false);
        jPanel14.setPreferredSize(new java.awt.Dimension(400, 227));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 153));
        jLabel33.setText("Ghi Chú");

        lblMaHoaDon_HoaDon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaHoaDon_HoaDon.setForeground(new java.awt.Color(0, 0, 153));
        lblMaHoaDon_HoaDon.setText("Số Hoá Đơn");

        lblTongTien_HoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTongTien_HoaDon.setForeground(new java.awt.Color(0, 0, 153));
        lblTongTien_HoaDon.setText("Giá");

        lblNgayNhapHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNgayNhapHoaDon.setForeground(new java.awt.Color(0, 0, 153));
        lblNgayNhapHoaDon.setText("Ngày Nhập Hoá Đơn");

        lblMaKhachHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMaKhachHang.setForeground(new java.awt.Color(0, 0, 153));
        lblMaKhachHang.setText("Mã Khách Hàng");
        lblMaKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaKhachHangMouseClicked(evt);
            }
        });

        txtGia.setEditable(false);
        txtGia.setBackground(new java.awt.Color(255, 255, 255));
        txtGia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGia.setForeground(new java.awt.Color(0, 0, 153));
        txtGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        btnThem_HoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnThem_HoaDon.setText("Thêm ");
        btnThem_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_HoaDonActionPerformed(evt);
            }
        });

        btnSua_HoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSua_HoaDon.setText("Sửa");
        btnSua_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_HoaDonActionPerformed(evt);
            }
        });

        btnReset_HoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnReset_HoaDon.setText("Reset");
        btnReset_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset_HoaDonActionPerformed(evt);
            }
        });

        lblMaNhanVien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(0, 0, 153));
        lblMaNhanVien.setText("Mã Nhân Viên");
        lblMaNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaNhanVienMouseClicked(evt);
            }
        });

        txtNgayLapHD.setDateFormatString("dd-MM-yyyy");

        txtGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));

        txtMaKhachHang.setEditable(false);
        txtMaKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        txtMaKhachHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaKhachHang.setForeground(new java.awt.Color(0, 0, 153));
        txtMaKhachHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));

        lblSoHD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSoHD.setForeground(new java.awt.Color(0, 0, 153));

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        txtMaNhanVien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaNhanVien.setForeground(new java.awt.Color(0, 0, 153));
        txtMaNhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(btnThem_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnSua_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMaHoaDon_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTongTien_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNgayNhapHoaDon)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaHoaDon_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(lblNgayNhapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_HoaDon)
                    .addComponent(btnSua_HoaDon)
                    .addComponent(btnReset_HoaDon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(204, 204, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Hoá Đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel19.setOpaque(false);
        jPanel19.setPreferredSize(new java.awt.Dimension(400, 230));

        lblMaCTPM.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaCTPM.setForeground(new java.awt.Color(0, 0, 153));
        lblMaCTPM.setText("Số Hoá Đơn");

        lblGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        lblGhiChu.setText("Ghi Chú");

        lblMaHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMaHoaDon.setForeground(new java.awt.Color(0, 0, 153));
        lblMaHoaDon.setText("Mã Sản Phẩm");

        jLabel40.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 153));
        jLabel40.setText("Số Lượng");

        txtMaSanPham_ChiTietHoaDon.setEditable(false);
        txtMaSanPham_ChiTietHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        txtMaSanPham_ChiTietHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaSanPham_ChiTietHoaDon.setForeground(new java.awt.Color(0, 0, 153));
        txtMaSanPham_ChiTietHoaDon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));

        txtSoLuong_ChiTietHoaDon.setEditable(false);
        txtSoLuong_ChiTietHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        txtSoLuong_ChiTietHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoLuong_ChiTietHoaDon.setForeground(new java.awt.Color(0, 0, 153));
        txtSoLuong_ChiTietHoaDon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));

        txtGhiChu_ChiTietHoaDon.setEditable(false);
        txtGhiChu_ChiTietHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        txtGhiChu_ChiTietHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu_ChiTietHoaDon.setForeground(new java.awt.Color(0, 0, 153));
        txtGhiChu_ChiTietHoaDon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));

        lblSCTH_ChiTietHoaDon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSCTH_ChiTietHoaDon.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaCTPM, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaSanPham_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSCTH_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaCTPM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSCTH_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSanPham_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblMaKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaKhachHangMouseClicked

    }//GEN-LAST:event_lblMaKhachHangMouseClicked

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    public String GetCbbSelected(JComboBox cbb) {
        Object[] obj = cbb.getSelectedObjects();
        displayvalueModel item = (displayvalueModel) obj[0];
        return item.displayvalue.toString();

    }
    private void btnThem_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_HoaDonActionPerformed

        String MakHachHang, MaNhanVien, Gia, GhiChu;
        Date NgayNhapHoaDon = txtNgayLapHD.getDate();
        MakHachHang = txtMaKhachHang.getText();
        MaNhanVien = txtMaNhanVien.getText();
        Gia = txtGia.getText();
        GhiChu = txtGhiChu.getText();
        HoaDon hd = new HoaDon(GhiChu, NgayNhapHoaDon, MakHachHang, MaNhanVien, Gia, GhiChu);
        ThongBao.ThongBaoDangNhap("Thông Báo", "Hoá Đơn " + NgayNhapHoaDon + " Đã Thêm Thành Công");
        BLLHoaDon.ThemHoaDon(hd);

        BLLHoaDon.LoadHoaDon(tblHoaDon);
        //LayDuLieuHoaDon();
    }//GEN-LAST:event_btnThem_HoaDonActionPerformed

    private void btnSua_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_HoaDonActionPerformed

        String MakHachHang, MaNhanVien, Gia, GhiChu;
        Date NgayNhapHoaDon = txtNgayLapHD.getDate();
        MakHachHang = txtMaKhachHang.getText();
        MaNhanVien = txtMaNhanVien.getText();
        Gia = txtGia.getText();
        GhiChu = txtGhiChu.getText();
        HoaDon hd = new HoaDon(GhiChu, NgayNhapHoaDon, MakHachHang, MaNhanVien, Gia, GhiChu);
        ThongBao.ThongBaoDangNhap("Thông Báo", "Hoá Đơn " + GhiChu + " Đã Sửa Thành Công");

        BLLHoaDon.UpdateHoaDon(hd);

        BLLHoaDon.LoadHoaDon(tblHoaDon);


    }//GEN-LAST:event_btnSua_HoaDonActionPerformed

    private void btnReset_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset_HoaDonActionPerformed
        this.btnSua_HoaDon.setEnabled(true);
        this.txtGhiChu.setText("");
        this.txtMaKhachHang.setText("");
        this.txtMaNhanVien.setText("");
        this.txtGia.setText("");
        this.lblSoHD.setText("");


    }//GEN-LAST:event_btnReset_HoaDonActionPerformed

    private void lblMaNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaNhanVienMouseClicked

    }//GEN-LAST:event_lblMaNhanVienMouseClicked

    private void tblChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietHoaDonMouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = tblChiTietHoaDon.getSelectedRow();
        lblSCTH_ChiTietHoaDon.setText(tblChiTietHoaDon.getValueAt(viTriDongVuaBam, 1).toString());
        txtMaSanPham_ChiTietHoaDon.setText(tblChiTietHoaDon.getValueAt(viTriDongVuaBam, 2).toString());
        txtSoLuong_ChiTietHoaDon.setText(tblChiTietHoaDon.getValueAt(viTriDongVuaBam, 3).toString());
        txtGhiChu_ChiTietHoaDon.setText(tblChiTietHoaDon.getValueAt(viTriDongVuaBam, 4).toString());
        LayDuLieuChiTietHoaDon(lblSoHD.getText());
    }//GEN-LAST:event_tblChiTietHoaDonMouseClicked

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVienActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int dongDuocChon = tblHoaDon.getSelectedRow();
        String SoHD = tblHoaDon.getValueAt(dongDuocChon, 1).toString();
        HoaDon nv = BLLHoaDon.LayHoaDonTheoMa(SoHD);
        lblSoHD.setText(nv.getSoHoaDon() + "");
        txtGhiChu.setText(nv.getGhiChu());
        txtGia.setText(nv.getGia());
        txtMaKhachHang.setText(nv.getMaKhachHang());
        txtMaNhanVien.setText(nv.getMaKhachHang());
        txtNgayLapHD.setDate(nv.getNgayNhapHoaDon());
        LayDuLieuChiTietHoaDon(lblSoHD.getText());
    }//GEN-LAST:event_tblHoaDonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset_HoaDon;
    private javax.swing.JButton btnSua_HoaDon;
    private javax.swing.JButton btnThem_HoaDon;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblMaCTPM;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaHoaDon_HoaDon;
    private javax.swing.JLabel lblMaKhachHang;
    public javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayNhapHoaDon;
    private javax.swing.JLabel lblSCTH_ChiTietHoaDon;
    private javax.swing.JLabel lblSoHD;
    private javax.swing.JLabel lblTongTien_HoaDon;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGhiChu_ChiTietHoaDon;
    private javax.swing.JTextField txtGia;
    public javax.swing.JTextField txtMaKhachHang;
    public javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMaSanPham_ChiTietHoaDon;
    private com.toedter.calendar.JDateChooser txtNgayLapHD;
    private javax.swing.JTextField txtSoLuong_ChiTietHoaDon;
    // End of variables declaration//GEN-END:variables
}
