/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASM_TT_GUI;

import ASM_TT_BLL.BLLKhachHang;
import ASM_TT_BLL.BLLNhanVien;
import ASM_TT_DTO.KhachHang;
import ASM_TT_DTO.NhanVien;
import ASM_TT_HALPER.HoTroNhapSo;
import ASM_TT_HALPER.ThongBao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author LENOVO
 */
public class TabKhachHang extends javax.swing.JPanel {

    public static String sql = "SELECT * FROM KhachHang";

    /**
     * Creates new form TabKhachHang
     */
    public TabKhachHang() {
        initComponents();
        BLLKhachHang.LoadKhachHang(tblDanhSach);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtDiaChi.setBackground(new Color(0, 0, 0, 0));
        txtSoCMND.setBackground(new Color(0, 0, 0, 0));
        txtHoTen.setBackground(new Color(0, 0, 0, 0));
        txtMaKH.setBackground(new Color(0, 0, 0, 0));
        txtSDT.setBackground(new Color(0, 0, 0, 0));
        txtTimKiem.setBackground(new Color(0, 0, 0, 0));
        txtGhiChu.setBackground(new Color(0, 0, 0, 0));
        txtThongBao.setBackground(new Color(0, 0, 0, 0));
        txtThongBao.setEnabled(false);

    }
    int tam = 0;
    ImageIcon icon;
    String imageLocation = "bg.jpg";
    String imageName;

    public boolean kiemtraimg(String imagePath) {
        boolean kiemanh;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
            kiemanh = true;
        } catch (IOException e) {
            kiemanh = false;
        }
        return kiemanh;
    }

    public void setLabelImage(String imagePath) {
        if (imagePath == null) {
            imagePath = "d:\\pictures\\laptop\\default.jpg";
        }
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {

        }
        icon = new ImageIcon(img);

        lblHinhAnh.setIcon(icon);

    }

    public void setLabelImage(String imageLocation, String imageName) {
        if (imageName == null) {
            imageName = "default.jpg";
        }
        imageLocation = this.imageLocation;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imageLocation + imageName));
        } catch (IOException e) {
        }
        icon = new ImageIcon(img);

        lblHinhAnh.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioiTinh = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        txtSoCMND = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        btnChonHinh = new javax.swing.JButton();
        lblHinhAnh = new javax.swing.JLabel();
        btnEdit = new keeptoo.KButton();
        btnSave = new keeptoo.KButton();
        btnDelete = new keeptoo.KButton();
        btnRefesh = new keeptoo.KButton();
        txtTimKiem = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        txtThongBao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setOpaque(false);

        lblMaKH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaKH.setForeground(new java.awt.Color(0, 0, 153));
        lblMaKH.setText("Mã Khách Hàng");

        txtMaKH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaKH.setForeground(new java.awt.Color(0, 0, 153));
        txtMaKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        txtHoTen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHoTen.setForeground(new java.awt.Color(0, 0, 153));
        txtHoTen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblHoTen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen.setText("Họ Tên");

        lblGioiTinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(0, 0, 153));
        lblGioiTinh.setText("Giới Tính");

        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        lblDiaChi.setText("Địa Chỉ");

        txtSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSDT.setForeground(new java.awt.Color(0, 0, 153));
        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtSDT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtSDTMouseMoved(evt);
            }
        });
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSDTKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
        });

        lblSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(0, 0, 153));
        lblSDT.setText("Số Điện Thoại");

        lblNgaySinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(0, 0, 153));
        lblNgaySinh.setText("Ghi Chú");

        txtSoCMND.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoCMND.setForeground(new java.awt.Color(0, 0, 153));
        txtSoCMND.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtSoCMND.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtSoCMNDMouseMoved(evt);
            }
        });
        txtSoCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoCMNDKeyReleased(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 153));
        lblEmail.setText("Số CMND");

        btnSearch.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM_TT_IMAGES/search.png"))); // NOI18N
        btnSearch.setText(" Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btgGioiTinh.add(rdbNam);
        rdbNam.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rdbNam.setForeground(new java.awt.Color(0, 0, 153));
        rdbNam.setSelected(true);
        rdbNam.setText("Nam");
        rdbNam.setOpaque(false);

        btgGioiTinh.add(rdbNu);
        rdbNu.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rdbNu.setForeground(new java.awt.Color(0, 0, 153));
        rdbNu.setText("Nữ");
        rdbNu.setOpaque(false);

        btnChonHinh.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnChonHinh.setText("Chọn Hình");
        btnChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHinhActionPerformed(evt);
            }
        });

        lblHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));

        btnEdit.setBorder(null);
        btnEdit.setText("Edit");
        btnEdit.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnEdit.setHideActionText(true);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setIconTextGap(45);
        btnEdit.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnEdit.setkBorderRadius(20);
        btnEdit.setkEndColor(new java.awt.Color(144, 80, 202));
        btnEdit.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnEdit.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnEdit.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnEdit.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnEdit.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnEdit.setkStartColor(new java.awt.Color(37, 184, 253));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setBorder(null);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSave.setHideActionText(true);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setIconTextGap(45);
        btnSave.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnSave.setkBorderRadius(20);
        btnSave.setkEndColor(new java.awt.Color(144, 80, 202));
        btnSave.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnSave.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnSave.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnSave.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnSave.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnSave.setkStartColor(new java.awt.Color(37, 184, 253));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBorder(null);
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnDelete.setHideActionText(true);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setIconTextGap(45);
        btnDelete.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnDelete.setkBorderRadius(20);
        btnDelete.setkEndColor(new java.awt.Color(144, 80, 202));
        btnDelete.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnDelete.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnDelete.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnDelete.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnDelete.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnDelete.setkStartColor(new java.awt.Color(37, 184, 253));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefesh.setBorder(null);
        btnRefesh.setText("Refresh");
        btnRefesh.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnRefesh.setHideActionText(true);
        btnRefesh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefesh.setIconTextGap(45);
        btnRefesh.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnRefesh.setkBorderRadius(20);
        btnRefesh.setkEndColor(new java.awt.Color(144, 80, 202));
        btnRefesh.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnRefesh.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnRefesh.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnRefesh.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnRefesh.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnRefesh.setkStartColor(new java.awt.Color(37, 184, 253));
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));

        txtGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });

        txtThongBao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtThongBao.setForeground(new java.awt.Color(0, 0, 153));
        txtThongBao.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnRefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSoCMND))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(15, 15, 15)
                                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(15, 15, 15)
                                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(rdbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChonHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Khách Hàng", "Họ Tên", "Giới Tính", "Địa Chỉ", "Số Điện Thoại", "CMND", "Ghi Chú"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(1).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHinhActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();

        if (evt.getSource() == btnChonHinh) {
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                String imagePath = file.getPath();
                setLabelImage(imagePath);
            } else {

            }
        }
    }//GEN-LAST:event_btnChonHinhActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here:
        int dongDuocChon = tblDanhSach.getSelectedRow();
        String MaKH = tblDanhSach.getValueAt(dongDuocChon, 1).toString();
        KhachHang nv = BLLKhachHang.LayKHTheoMa(MaKH);
        txtMaKH.setText(nv.getMaKhachHang() + "");
        txtHoTen.setText(nv.getTenKhachHang());
        if (nv.isGioiTinh()) {
            rdbNam.setSelected(true);
        } else {
            rdbNu.setSelected(true);
        }
        txtDiaChi.setText(nv.getDiaChi());
        txtSDT.setText(nv.getSDT());
        txtGhiChu.setText(nv.getGhiChu());
        txtSoCMND.setText(nv.getSoCMND());
        
        txtThongBao.setEnabled(false);
        // Chuyển Về Tab Đầu Tiên


    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String MaKhachHang = txtMaKH.getText();
        String TenKhachHang = txtHoTen.getText();
        boolean GioiTinh = rdbNam.isSelected();
        String DiaChi = txtDiaChi.getText();
        String SDT = txtSDT.getText();
        String SoCMND = txtSoCMND.getText();
        String GhiChu = txtGhiChu.getText();
        if (this.txtMaKH.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Bạn Chưa Chọn Dòng Để Sửa ");
        } else {
            KhachHang KH = new KhachHang(MaKhachHang, TenKhachHang, GioiTinh, DiaChi, SDT, SoCMND, GhiChu);
            //ThongBao.ThongBaoDangNhap("Thông Báo", " Mã Khách Hàng " + MaKhachHang + " Được Sửa Thành Công");
            BLLKhachHang.UpdateKhachHang(KH);
            BLLKhachHang.LoadKhachHang(tblDanhSach);
        }


        /* String MaNhanVien = txtMaNV.getText();
        String MaChucVu = cbbMaChucVu.getSelectedItem().toString();
        String HoTen = txtHoTen.getText();
        boolean GioiTinh = rdbNam.isSelected();
        Date NgaySinh = txt_DateSinh.getDate();
        String DiaChi = txtDiaChi.getText();
        String SDT = txtSoDienThoai.getText();
        String SoCMND = txtSoCMND.getText();
        Date NgayVaoLam = txt_DateNgayVaoLam.getDate();
        String Email = txtEmail.getText();

        NhanVien nv = new NhanVien(MaNhanVien, MaChucVu, HoTen, GioiTinh, NgaySinh, DiaChi, SDT, SoCMND, NgayVaoLam, Email);
        ThongBao.ThongBaoDangNhap("Thông Báo", " Mã " + MaNhanVien + " Được Thêm Thành Công");
        BLLNhanVien.ThemNhanVien(nv);
        BLLNhanVien.LoadNhanVien(tblDanhSach);*/

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String TenKhachHang = txtHoTen.getText();
        boolean GioiTinh = rdbNam.isSelected();
        String DiaChi = txtDiaChi.getText();
        String SDT = txtSDT.getText();
        String SoCMND = txtSoCMND.getText();
        String GhiChu = txtGhiChu.getText();
        if (this.txtMaKH.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Mã Nhân Viên Không Được Bỏ Trống");
        } else if (this.txtHoTen.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Họ Và Tên Không Được Bỏ Trống");
        } else if (this.txtDiaChi.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Địa Chỉ Không Được Bỏ Trống");
        } else if (this.txtSDT.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Số CMND Không Được Bỏ Trống");
        } else if (this.txtSoCMND.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Email Không Được Bỏ Trống");
        } else {
            KhachHang KH = new KhachHang(TenKhachHang, GioiTinh, DiaChi, SDT, SoCMND, GhiChu);
            //ThongBao.ThongBaoDangNhap("Thông Báo", " Mã Khách Hàng " + MaKhachHang + " Được Thêm Thành Công");
            BLLKhachHang.ThemKhachHang(KH);
            BLLKhachHang.LoadKhachHang(tblDanhSach);
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (this.txtMaKH.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Bạn Chưa Chọn Dòng Để Xoá !!");

        } else {

            int DSViTri[] = tblDanhSach.getSelectedRows();
            List<String> lstMaSP = new ArrayList<>();

            for (int i : DSViTri) {
                String MaKH = tblDanhSach.getValueAt(i, 1).toString();
                lstMaSP.add(MaKH);
            }

            BLLKhachHang.Delete(lstMaSP);

            BLLKhachHang.LoadKhachHang(tblDanhSach);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        // TODO add your handling code here:
        this.btnSave.setEnabled(true);
        this.txtDiaChi.setText("");
        this.txtSoCMND.setText("");
        this.txtHoTen.setText("");
        this.txtSDT.setText("");
        this.txtMaKH.setText("");
        txtThongBao.setEnabled(false);
        

    }//GEN-LAST:event_btnRefeshActionPerformed

    private void txtSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyPressed
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSDTKeyPressed

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSDTKeyReleased

    private void txtSDTMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTMouseMoved
        // TODO add your handling code here:
        txtSDT.setToolTipText("Số điện thoại có 10 số và bắt đầu bằng số 0.");
    }//GEN-LAST:event_txtSDTMouseMoved

    private void txtSoCMNDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoCMNDKeyReleased
        // TODO add your handling code here:
        /*String Email_Pattern = "^[a-zA-Z0-9]{0,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(Email_Pattern);
        Matcher matcher = pattern.matcher(txtSoCMND.getText());
        if (!matcher.matches()) {
            System.out.println("Email không đúng định Dạng");
        } else {
            System.out.println("");
        }*/
        HoTroNhapSo.luonNhapSo(evt);

    }//GEN-LAST:event_txtSoCMNDKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (this.txtTimKiem.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Bạn Chưa Nhập Từ Khoá Cần Tìm");
        } else {
            String TenNhanVien = "%" + txtTimKiem.getText() + "%";          
            BLLKhachHang.TimKhachHang(tblDanhSach, TenNhanVien);
            

        }
        txtThongBao.setEnabled(true);
            txtThongBao.setText("Có " + tblDanhSach.getRowCount() + "Tên Khách Hàng Cần Tìm");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtSoCMNDMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoCMNDMouseMoved
        txtSDT.setToolTipText("Số CMND có 9 số. ");
    }//GEN-LAST:event_txtSoCMNDMouseMoved

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGioiTinh;
    private javax.swing.JButton btnChonHinh;
    private keeptoo.KButton btnDelete;
    private keeptoo.KButton btnEdit;
    private keeptoo.KButton btnRefesh;
    private keeptoo.KButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtThongBao;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
