/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASM_TT_GUI;

import ASM_TT_BLL.BLLNhaCungCap;
import ASM_TT_DTO.NhaCungCap;
import ASM_TT_HALPER.HoTroNhapSo;
import ASM_TT_HALPER.ThongBao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author LENOVO
 */
public class TabNhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public TabNhaCungCap() {
        initComponents();
        BLLNhaCungCap.LoadNCC(tblNhaCC);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);     
        txtDiaChi.setBackground(new Color(0, 0, 0, 0));
        txtMaNhaCC.setBackground(new Color(0, 0, 0, 0));
        txtSDT.setBackground(new Color(0, 0, 0, 0));
        txtTenNhaCC.setBackground(new Color(0, 0, 0, 0));
        txtGhiChu.setBackground(new Color(0, 0, 0, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNhaCC = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        lblSoCMND = new javax.swing.JLabel();
        txtTenNhaCC = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        btnSave = new keeptoo.KButton();
        btnEdit = new keeptoo.KButton();
        btnDelete = new keeptoo.KButton();
        btnNhapMoi = new keeptoo.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhaCC = new javax.swing.JTable();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setOpaque(false);

        lblMaNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(0, 0, 153));
        lblMaNV.setText("Mã NCC");

        txtMaNhaCC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaNhaCC.setForeground(new java.awt.Color(0, 0, 153));
        txtMaNhaCC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblHoTen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen.setText("Tên NCC");

        lblSoCMND.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSoCMND.setForeground(new java.awt.Color(0, 0, 153));
        lblSoCMND.setText("Ghi Chú");

        txtTenNhaCC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenNhaCC.setForeground(new java.awt.Color(0, 0, 153));
        txtTenNhaCC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        txtSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSDT.setForeground(new java.awt.Color(0, 0, 153));
        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtSDT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtSDTMouseMoved(evt);
            }
        });
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
        });

        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        lblDiaChi.setText("Địa Chỉ");

        lblSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(0, 0, 153));
        lblSDT.setText("Số Điện Thoại");

        txtGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        btnSave.setBorder(null);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSave.setHideActionText(true);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setIconTextGap(45);
        btnSave.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnSave.setkBorderRadius(20);
        btnSave.setkEndColor(new java.awt.Color(144, 80, 202));
        btnSave.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnSave.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnSave.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnSave.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnSave.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnSave.setkStartColor(new java.awt.Color(37, 184, 253));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBorder(null);
        btnEdit.setText("Edit");
        btnEdit.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnEdit.setHideActionText(true);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setIconTextGap(45);
        btnEdit.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnEdit.setkBorderRadius(20);
        btnEdit.setkEndColor(new java.awt.Color(144, 80, 202));
        btnEdit.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnEdit.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnEdit.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnEdit.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnEdit.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnEdit.setkStartColor(new java.awt.Color(37, 184, 253));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBorder(null);
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnDelete.setHideActionText(true);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setIconTextGap(45);
        btnDelete.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnDelete.setkBorderRadius(20);
        btnDelete.setkEndColor(new java.awt.Color(144, 80, 202));
        btnDelete.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnDelete.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnDelete.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnDelete.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnDelete.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnDelete.setkStartColor(new java.awt.Color(37, 184, 253));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNhapMoi.setBorder(null);
        btnNhapMoi.setText("Refresh");
        btnNhapMoi.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnNhapMoi.setHideActionText(true);
        btnNhapMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapMoi.setIconTextGap(45);
        btnNhapMoi.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnNhapMoi.setkBorderRadius(20);
        btnNhapMoi.setkEndColor(new java.awt.Color(144, 80, 202));
        btnNhapMoi.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnNhapMoi.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnNhapMoi.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnNhapMoi.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnNhapMoi.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnNhapMoi.setkStartColor(new java.awt.Color(37, 184, 253));
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(txtMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGhiChu)))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        tblNhaCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Số Điện Thoại", "Địa Chỉ", "Ghi Chú"
            }
        ));
        tblNhaCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaCCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhaCC);
        if (tblNhaCC.getColumnModel().getColumnCount() > 0) {
            tblNhaCC.getColumnModel().getColumn(0).setMinWidth(70);
            tblNhaCC.getColumnModel().getColumn(0).setMaxWidth(70);
            tblNhaCC.getColumnModel().getColumn(1).setMinWidth(0);
            tblNhaCC.getColumnModel().getColumn(1).setMaxWidth(0);
            tblNhaCC.getColumnModel().getColumn(5).setMinWidth(100);
            tblNhaCC.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2)
                .addGap(40, 40, 40))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String TenNCC = txtTenNhaCC.getText();
        String SDT = txtSDT.getText();
        String DiaChi = txtDiaChi.getText();
        String GhiChu = txtGhiChu.getText();
        if (this.txtTenNhaCC.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Mã Nhân Viên Không Được Bỏ Trống");
        } else if (this.txtSDT.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Họ Và Tên Không Được Bỏ Trống");
        } else if (this.txtDiaChi.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Địa Chỉ Không Được Bỏ Trống");
        } else {
            NhaCungCap ncc = new NhaCungCap(TenNCC, SDT, DiaChi, GhiChu);
            BLLNhaCungCap.ThemNhaCC(ncc);
            BLLNhaCungCap.LoadNCC(tblNhaCC);
            ThongBao.ThongBaoSQL("Thông Báo", "Thêm thành công.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String MaNCC = txtMaNhaCC.getText();
        String TenNCC = txtTenNhaCC.getText();
        String SDT = txtSDT.getText();
        String DiaChi = txtDiaChi.getText();
        String GhiChu = txtGhiChu.getText();
        if (this.txtTenNhaCC.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Mã Nhân Viên Không Được Bỏ Trống");
        } else if (this.txtSDT.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Họ Và Tên Không Được Bỏ Trống");
        } else if (this.txtDiaChi.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Địa Chỉ Không Được Bỏ Trống");
        } else {
            NhaCungCap ncc = new NhaCungCap(MaNCC, TenNCC, SDT, DiaChi, GhiChu);
            BLLNhaCungCap.UpdateNhaCC(ncc);
            BLLNhaCungCap.LoadNCC(tblNhaCC);
            ThongBao.ThongBaoSQL("Thông Báo", "Sửa thành công.");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       if (this.txtMaNhaCC.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Bạn Chưa Chọn Dòng Để Xoá !!");

        } else {

            int DSViTri[] = tblNhaCC.getSelectedRows();
            List<String> lstMaSP = new ArrayList<>();

            for (int i : DSViTri) {
                String MaNV = tblNhaCC.getValueAt(i, 1).toString();
                lstMaSP.add(MaNV);
            }

            BLLNhaCungCap.Delete(lstMaSP);

            BLLNhaCungCap.LoadNCC(tblNhaCC);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        txtMaNhaCC.setText("");
        txtTenNhaCC.setText("");
        txtSDT.setText("");
        txtDiaChi.setText("");
        txtGhiChu.setText("");
      
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void tblNhaCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaCCMouseClicked
        int dongDuocChon = tblNhaCC.getSelectedRow();
        String MaNCC = tblNhaCC.getValueAt(dongDuocChon, 1).toString();
        NhaCungCap ncc = BLLNhaCungCap.LayNCCTheoMa(MaNCC);
        txtMaNhaCC.setText(ncc.getMaNCC() + "");
        txtTenNhaCC.setText(ncc.getTenNCC());
        txtSDT.setText(ncc.getSDT());
        txtDiaChi.setText(ncc.getDiaChi());
        txtGhiChu.setText(ncc.getGhiChu());
    }//GEN-LAST:event_tblNhaCCMouseClicked

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSDTKeyReleased

    private void txtSDTMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTMouseMoved
        txtSDT.setToolTipText("Số điện thoại có 10 số và bắt đầu bằng số 0.");
    }//GEN-LAST:event_txtSDTMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnDelete;
    private keeptoo.KButton btnEdit;
    private keeptoo.KButton btnNhapMoi;
    private keeptoo.KButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSoCMND;
    private javax.swing.JTable tblNhaCC;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaNhaCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNhaCC;
    // End of variables declaration//GEN-END:variables
}
