package ASM_TT_GUI;

import ASM_TT_BLL.BLLCombobox;
import ASM_TT_BLL.BLLSanPham;
import ASM_TT_BLL.BLLNhanVien;
import ASM_TT_DAL.DALNhanVien;
import ASM_TT_DTO.NhanVien;
import ASM_TT_DTO.SanPham;
import ASM_TT_HALPER.ChuyenDoi;
import ASM_TT_HALPER.HoTroNhapSo;
import ASM_TT_HALPER.Mycombobox;
import ASM_TT_HALPER.SetImage;
import ASM_TT_HALPER.ThongBao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

public class TabNhanVien extends javax.swing.JPanel {
    
     SetImage img = new SetImage();

    public static String sql = "SELECT * FROM NhanVien";
    
    public TabNhanVien() {
        initComponents();
        BLLNhanVien.LoadNhanVien(tblDanhSach);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtDiaChi.setBackground(new Color(0, 0, 0, 0));
        txtHoTen.setBackground(new Color(0, 0, 0, 0));
        txtMaNV.setBackground(new Color(0, 0, 0, 0));
        txtSoDienThoai.setBackground(new Color(0, 0, 0, 0));
        txtSoCMND.setBackground(new Color(0, 0, 0, 0));
        txtLuong.setBackground(new Color(0, 0, 0, 0));
        txtTimKiem.setBackground(new Color(0, 0, 0, 0));
        txtThongBao.setBackground(new Color(0, 0, 0, 0));
        txtTenDangNhap.setBackground(new Color(0, 0, 0, 0));
        txtMatKhau.setBackground(new Color(0, 0, 0, 0));
        txtThongBao.setEnabled(false);
       

        //loadDataComboChucVu();

    }

    int tam = 0;
    ImageIcon icon;
    String imageLocation = "bg.jpg";
    String imageName;

    private void loadDataComboChucVu() {

        BLLNhanVien.LoadChucVu(cbbMaChucVu);
    }

    public boolean kiemtraimg(String imagePath) {
        boolean kiemanh;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
            kiemanh = true;
        } catch (IOException e) {
            kiemanh = false;
        }
        return kiemanh;
    }

    public void setLabelImage(String imagePath) {
        if (imagePath == null) {
            imagePath = "d:\\pictures\\laptop\\default.jpg";
        }
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {

        }
        icon = new ImageIcon(img);

        lblHinhAnh.setIcon(icon);

    }

    public void setLabelImage(String imageLocation, String imageName) {
        if (imageName == null) {
            imageName = "default.jpg";
        }
        imageLocation = this.imageLocation;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imageLocation + imageName));
        } catch (IOException e) {
        }
        icon = new ImageIcon(img);

        lblHinhAnh.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioiTinh = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblMaCV = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSoCMND = new javax.swing.JTextField();
        lblSoCMND = new javax.swing.JLabel();
        lblNgayVaoLam = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        lblLuong = new javax.swing.JLabel();
        txt_DateSinh = new com.toedter.calendar.JDateChooser();
        txt_DateNgayVaoLam = new com.toedter.calendar.JDateChooser();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        cbbMaChucVu = new javax.swing.JComboBox<>();
        btnSave = new keeptoo.KButton();
        btnEdit = new keeptoo.KButton();
        btnDelete = new keeptoo.KButton();
        btnNhapMoi = new keeptoo.KButton();
        btnChonHinh = new javax.swing.JButton();
        lblHinhAnh = new javax.swing.JLabel();
        TimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        lblDiaChi1 = new javax.swing.JLabel();
        txtThongBao = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        lblDiaChi2 = new javax.swing.JLabel();
        cbbTimCV = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        txtHinhAnh = new javax.swing.JTextField();
        txtTenDangNhap = new javax.swing.JTextField();

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkGradientFocus(700);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setOpaque(false);

        lblMaNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(0, 0, 153));
        lblMaNV.setText("Mã Nhân Viên");

        txtMaNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(0, 0, 153));
        txtMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblMaCV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMaCV.setForeground(new java.awt.Color(0, 0, 153));
        lblMaCV.setText("Chức Vụ");

        txtHoTen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHoTen.setForeground(new java.awt.Color(0, 0, 153));
        txtHoTen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblHoTen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen.setText("Họ Tên");

        lblGioiTinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(0, 0, 153));
        lblGioiTinh.setText("Giới Tính");

        lblNgaySinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(0, 0, 153));
        lblNgaySinh.setText("Ngày Sinh");

        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        lblDiaChi.setText("Địa Chỉ");

        txtSoDienThoai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(0, 0, 153));
        txtSoDienThoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtSoDienThoai.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtSoDienThoaiMouseMoved(evt);
            }
        });
        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyReleased(evt);
            }
        });

        lblSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(0, 0, 153));
        lblSDT.setText("Số Điện Thoại");

        txtSoCMND.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoCMND.setForeground(new java.awt.Color(0, 0, 153));
        txtSoCMND.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtSoCMND.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtSoCMNDMouseMoved(evt);
            }
        });
        txtSoCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoCMNDKeyPressed(evt);
            }
        });

        lblSoCMND.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSoCMND.setForeground(new java.awt.Color(0, 0, 153));
        lblSoCMND.setText("Số CMND");

        lblNgayVaoLam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNgayVaoLam.setForeground(new java.awt.Color(0, 0, 153));
        lblNgayVaoLam.setText("Ngày Vào Làm");

        txtLuong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLuong.setForeground(new java.awt.Color(0, 0, 153));
        txtLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLuongKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLuongKeyReleased(evt);
            }
        });

        lblLuong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLuong.setForeground(new java.awt.Color(0, 0, 153));
        lblLuong.setText("Lương");

        txt_DateSinh.setForeground(new java.awt.Color(0, 0, 153));
        txt_DateSinh.setDateFormatString("dd-MM-yyyy");
        txt_DateSinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txt_DateNgayVaoLam.setForeground(new java.awt.Color(0, 0, 153));
        txt_DateNgayVaoLam.setDateFormatString("dd-MM-yyyy");
        txt_DateNgayVaoLam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btgGioiTinh.add(rdbNam);
        rdbNam.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rdbNam.setForeground(new java.awt.Color(0, 0, 153));
        rdbNam.setSelected(true);
        rdbNam.setText("Nam");
        rdbNam.setOpaque(false);

        btgGioiTinh.add(rdbNu);
        rdbNu.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rdbNu.setForeground(new java.awt.Color(0, 0, 153));
        rdbNu.setText("Nữ");
        rdbNu.setOpaque(false);

        cbbMaChucVu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbbMaChucVu.setForeground(new java.awt.Color(0, 0, 204));
        cbbMaChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Bảo vệ", "Thu ngân", "Trưởng phòng", "Tổ trưởng", " " }));

        btnSave.setBorder(null);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSave.setHideActionText(true);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setIconTextGap(45);
        btnSave.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnSave.setkBorderRadius(20);
        btnSave.setkEndColor(new java.awt.Color(144, 80, 202));
        btnSave.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnSave.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnSave.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnSave.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnSave.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnSave.setkStartColor(new java.awt.Color(37, 184, 253));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBorder(null);
        btnEdit.setText("Edit");
        btnEdit.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnEdit.setHideActionText(true);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setIconTextGap(45);
        btnEdit.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnEdit.setkBorderRadius(20);
        btnEdit.setkEndColor(new java.awt.Color(144, 80, 202));
        btnEdit.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnEdit.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnEdit.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnEdit.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnEdit.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnEdit.setkStartColor(new java.awt.Color(37, 184, 253));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBorder(null);
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnDelete.setHideActionText(true);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setIconTextGap(45);
        btnDelete.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnDelete.setkBorderRadius(20);
        btnDelete.setkEndColor(new java.awt.Color(144, 80, 202));
        btnDelete.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnDelete.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnDelete.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnDelete.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnDelete.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnDelete.setkStartColor(new java.awt.Color(37, 184, 253));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNhapMoi.setBorder(null);
        btnNhapMoi.setText("Refresh");
        btnNhapMoi.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnNhapMoi.setHideActionText(true);
        btnNhapMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapMoi.setIconTextGap(45);
        btnNhapMoi.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnNhapMoi.setkBorderRadius(20);
        btnNhapMoi.setkEndColor(new java.awt.Color(144, 80, 202));
        btnNhapMoi.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnNhapMoi.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnNhapMoi.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnNhapMoi.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnNhapMoi.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnNhapMoi.setkStartColor(new java.awt.Color(37, 184, 253));
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        btnChonHinh.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnChonHinh.setText("Chọn Hình");
        btnChonHinh.setIconTextGap(5);
        btnChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHinhActionPerformed(evt);
            }
        });

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));

        TimKiem.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM_TT_IMAGES/search.png"))); // NOI18N
        TimKiem.setText(" Search");
        TimKiem.setIconTextGap(5);
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimKiem.setForeground(new java.awt.Color(0, 0, 153));
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        lblDiaChi1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi1.setForeground(new java.awt.Color(0, 0, 153));
        lblDiaChi1.setText("Tên Đăng Nhập");

        txtThongBao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtThongBao.setForeground(new java.awt.Color(0, 0, 153));
        txtThongBao.setBorder(null);
        txtThongBao.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtMatKhau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(0, 0, 153));
        txtMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblDiaChi2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi2.setForeground(new java.awt.Color(0, 0, 153));
        lblDiaChi2.setText("Mật Khẩu");

        cbbTimCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Nhân viên", "Bảo vệ", "Thu ngân", "Trưởng phòng", "Tổ trưởng", " " }));
        cbbTimCV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTimCVItemStateChanged(evt);
            }
        });

        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Nhân Viên", "Họ Tên", "Giới Tính", "Ngày Sinh", "Chức Vụ", "Lương", "SDT", "Địa chỉ", "Số CMND", "Tên Đăng Nhập", "Mập Khẩu", "Ngày Vào Làm", "Hình ảnh"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(1).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(1).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(3).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(10).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(10).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(11).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        txtHinhAnh.setEditable(false);
        txtHinhAnh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHinhAnh.setForeground(new java.awt.Color(0, 0, 153));
        txtHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        txtTenDangNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenDangNhap.setForeground(new java.awt.Color(0, 0, 153));
        txtTenDangNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMaNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMaCV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbbMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(35, 35, 35))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(25, 25, 25))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_DateSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(rdbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(40, 40, 40)
                                                    .addComponent(rdbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(22, 22, 22))))))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(35, 35, 35)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_DateNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(lblLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDiaChi2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(cbbTimCV, 0, 90, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnChonHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(txtHinhAnh))
                                .addContainerGap())))
                    .addComponent(jScrollPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rdbNam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_DateSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_DateNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbTimCV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here
        int dongDuocChon = tblDanhSach.getSelectedRow();
        String MaNV = tblDanhSach.getValueAt(dongDuocChon, 1).toString();
        NhanVien nv = BLLNhanVien.LayNhanVienTheoMa(MaNV);
        txtMaNV.setText(nv.getMaNV()+ "");
        String image = (String) tblDanhSach.getValueAt(dongDuocChon, 13);

        //   cbbMaChucVu.setSelectedItem(nv.getMaChucVu());
        //BLLCombobox.setComboSelectValue(cbbMaChucVu, nv.getChucVu());

        
        txtHoTen.setText(nv.getTenNV());
        if (nv.isGioiTinh()) {
            rdbNam.setSelected(true);
        } else {
            rdbNu.setSelected(true);
        }

        txt_DateSinh.setDate(nv.getNgaySinh());
        txtDiaChi.setText(nv.getDiaChi());
        txtSoDienThoai.setText(nv.getSDT());
        txtSoCMND.setText(nv.getCMND());
        txtLuong.setText(ChuyenDoi.LaySoString(nv.getLuong()));
        //txtEmail.setText(nv.getEmail());
        txtThongBao.setText(nv.getTenDangNhap());
        txtTenDangNhap.setText(nv.getTenDangNhap());
        txtMatKhau.setText(nv.getMatKhau());
        txt_DateNgayVaoLam.setDate(nv.getNgayVaoLam());
        txtHinhAnh.setText(image);
       img.setImageLabel(lblHinhAnh, "image//" + image);
       
        
        // Chuyển Về Tab Đầu Tiên
        lblHinhAnh.setText("");

    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHinhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("image");
        FileFilter filter = new FileNameExtensionFilter("Image file", "gjf", "jpg", "png");

        fileChooser.setFileFilter(filter);
        fileChooser.setMultiSelectionEnabled(false);

        int action = fileChooser.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            while (true) {
                if (!fileChooser.getSelectedFile().getName().matches("([^\\s]+(\\.(?i)(jpg|png|gif|bmp))$)")) {
                    JOptionPane.showMessageDialog(null, "Định dạng file hình đuôi phải là GIF, JPG, PNG !");
                    return;
                } else {
                    break;
                }
            }
            String imgFile = fileChooser.getSelectedFile().getName();
            txtHinhAnh.setText(imgFile);
            img.setImageLabel(lblHinhAnh, "image//" + imgFile);
        }
    }//GEN-LAST:event_btnChonHinhActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        String TenNV = txtHoTen.getText();
        boolean GioiTinh = rdbNam.isSelected();
        Date NgaySinh = txt_DateSinh.getDate();
        String ChucVu = cbbMaChucVu.getSelectedItem().toString();
        double Luong = ChuyenDoi.LaySoDouble(txtLuong.getText());
        String SDT = txtSoDienThoai.getText();
        String DiaChi = txtDiaChi.getText();
        String SoCMND = txtSoCMND.getText();
        Date NgayVaoLam = txt_DateNgayVaoLam.getDate();
        String TenDangNhap = txtThongBao.getText();
        String MatKhau = txtMatKhau.getText();
        String HinhAnh = txtHinhAnh.getText();
        if (this.txtMaNV.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Mã Nhân Viên Không Được Bỏ Trống");
        } else if (this.txtHoTen.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Họ Và Tên Không Được Bỏ Trống");
        } else if (this.txtDiaChi.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Địa Chỉ Không Được Bỏ Trống");
        } else if (this.txtSoCMND.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Số CMND Không Được Bỏ Trống");
        } else if (this.txtLuong.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Email Không Được Bỏ Trống");
        } else if (this.txtSoDienThoai.getText().length() < 10) {
            ThongBao.ThongBaoSQL("Thông Báo", "Số Điện Thoại Được Bỏ Trống");
        } else if (this.txtThongBao.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Tên Đăng Nhập Được Bỏ Trống");
        } else if (this.txtMatKhau.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Mật Khẩu Được Bỏ Trống");
        } else {
            NhanVien nv = new NhanVien(TenNV, GioiTinh, NgaySinh, ChucVu, Luong, DiaChi, SDT, SoCMND, NgayVaoLam, TenDangNhap, MatKhau, HinhAnh);
            
            BLLNhanVien.ThemNhanVien(nv);
            BLLNhanVien.LoadNhanVien(tblDanhSach);
        }
        /* String MaNhanVien = txtMaNV.getText();
        String MaChucVu = cbbMaChucVu.getSelectedItem().toString();
        String HoTen = txtHoTen.getText();
        boolean GioiTinh = rdbNam.isSelected();
        Date NgaySinh = txt_DateSinh.getDate();
        String DiaChi = txtDiaChi.getText();
        String SDT = txtSoDienThoai.getText();
        String SoCMND = txtSoCMND.getText();
        Date NgayVaoLam = txt_DateNgayVaoLam.getDate();
        String Email = txtEmail.getText();

        NhanVien nv = new NhanVien(MaNhanVien, MaChucVu, HoTen, GioiTinh, NgaySinh, DiaChi, SDT, SoCMND, NgayVaoLam, Email);
        ThongBao.ThongBaoDangNhap("Thông Báo", " Mã " + MaNhanVien + " Được Thêm Thành Công");
        BLLNhanVien.ThemNhanVien(nv);
        BLLNhanVien.LoadNhanVien(tblDanhSach);*/


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        this.btnSave.setEnabled(true);
        this.txtDiaChi.setText("");
        this.txtLuong.setText("");
        this.txtHoTen.setText("");
        this.txtMaNV.setText("");
        this.txtSoCMND.setText("");
        this.txtSoDienThoai.setText("");
        this.txtThongBao.setText("");
        this.txtMatKhau.setText("");

    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.btnSave.setEnabled(false);
        String MaNV = txtMaNV.getText();
        String TenNV = txtHoTen.getText();
        boolean GioiTinh = rdbNam.isSelected();
        Date NgaySinh = txt_DateSinh.getDate();
        String ChucVu = cbbMaChucVu.getSelectedItem().toString();
        double Luong = ChuyenDoi.LaySoDouble(txtLuong.getText());
        String SDT = txtSoDienThoai.getText();
        String DiaChi = txtDiaChi.getText();
        String SoCMND = txtSoCMND.getText();
        Date NgayVaoLam = txt_DateNgayVaoLam.getDate();
        String TenDangNhap = txtThongBao.getText();
        String MatKhau = txtMatKhau.getText();
        String HinhAnh = txtHinhAnh.getText();
        
        if (this.txtMaNV.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Bạn Chưa Chọn Dòng Để Sửa !!");
        } else {
            NhanVien nv = new NhanVien(MaNV, TenNV, GioiTinh, NgaySinh, ChucVu, Luong, DiaChi, SDT, SoCMND, NgayVaoLam, TenDangNhap, MatKhau, HinhAnh);
            //ThongBao.ThongBaoDangNhap("Thông Báo", " Mã Nhân Viên " + MaNhanVien + " Được Sửa Thành Công");
            BLLNhanVien.UpdateNhanVien(nv);
            BLLNhanVien.LoadNhanVien(tblDanhSach);
        
        /*String MaNhanVien = txtMaNV.getText();
        String MaChucVu = cbbMaChucVu.getSelectedItem().toString();
        String HoTen = txtHoTen.getText();
        boolean GioiTinh = rdbNam.isSelected();
        Date NgaySinh = txt_DateSinh.getDate();
        String DiaChi = txtDiaChi.getText();
        String SDT = txtSoDienThoai.getText();
        String SoCMND = txtSoCMND.getText();
        Date NgayVaoLam = txt_DateNgayVaoLam.getDate();
        String Email = txtEmail.getText();

        NhanVien nv = new NhanVien(MaNhanVien, MaChucVu, HoTen, GioiTinh, NgaySinh, DiaChi, SDT, SoCMND, NgayVaoLam, Email);
        ThongBao.ThongBaoDangNhap("Thông Báo", " Mã " + MaNhanVien + " Được Sửa Thành Công");
        BLLNhanVien.UpdateNhanVien(nv);
        BLLNhanVien.LoadNhanVien(tblDanhSach);*/
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtSoDienThoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyPressed
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSoDienThoaiKeyPressed

    private void txtSoDienThoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyReleased
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSoDienThoaiKeyReleased

    private void txtSoDienThoaiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoDienThoaiMouseMoved
        // TODO add your handling code here:
        txtSoDienThoai.setToolTipText("Số điện thoại có 10 số và bắt đầu bằng số 0.");
    }//GEN-LAST:event_txtSoDienThoaiMouseMoved

    private void txtSoCMNDMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoCMNDMouseMoved
        // TODO add your handling code here:
        txtSoCMND.setToolTipText("Số CMND từ 0 đến 10 số.");
    }//GEN-LAST:event_txtSoCMNDMouseMoved

    private void txtSoCMNDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoCMNDKeyPressed
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSoCMNDKeyPressed

    private void txtLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongKeyReleased
       /* // TODO add your handling code here:
        String Email_Pattern = "^[a-zA-Z0-9]{0,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(Email_Pattern);
        Matcher matcher = pattern.matcher(txtEmail.getText());
        if (!matcher.matches()) {
            System.out.println("Email không đúng định Dạng");
        } else {
            System.out.println("");
        }*/
        HoTroNhapSo.luonNhapSo(evt);

    }//GEN-LAST:event_txtLuongKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (this.txtMaNV.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Bạn Chưa Chọn Dòng Để Xoá !!");

        } else {

            int DSViTri[] = tblDanhSach.getSelectedRows();
            List<String> lstMaSP = new ArrayList<>();

            for (int i : DSViTri) {
                String MaNV = tblDanhSach.getValueAt(i, 1).toString();
                lstMaSP.add(MaNV);
            }

            BLLNhanVien.Delete(lstMaSP);

            BLLNhanVien.LoadNhanVien(tblDanhSach);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
        // TODO add your handling code here:
        /*if (this.txtTimKiem.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Bạn Chưa Nhập Từ Khoá Cần Tìm");
        } else {
            String TenNhanVien = "%" + txtTimKiem.getText() + "%";
            String ChucVu =  cbbTimCV.getSelectedItem().toString();
            BLLNhanVien.TimNhanVien(tblDanhSach, TenNhanVien, ChucVu);
            txtTimKiem.setText("Có " + tblDanhSach.getRowCount() + "Tên Nhân Viên Cần Tìm");

        }*/
            String TenNhanVien = "%" + txtTimKiem.getText() + "%";
            String ChucVu =  cbbTimCV.getSelectedItem().toString();
            BLLNhanVien.TimNhanVien(tblDanhSach, TenNhanVien, ChucVu);
            txtThongBao.setEnabled(true);
            txtThongBao.setText("Có " + tblDanhSach.getRowCount() + "Tên Nhân Viên Cần Tìm");


    }//GEN-LAST:event_TimKiemActionPerformed

    private void txtLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongKeyPressed
        // TODO add your handling code here:
         txtLuong.setToolTipText("Lương Phải Được Nhập Bằng Số .");
    }//GEN-LAST:event_txtLuongKeyPressed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void cbbTimCVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTimCVItemStateChanged
        String TenNhanVien = "%" + txtTimKiem.getText() + "%";
            String ChucVu =  cbbTimCV.getSelectedItem().toString();
            BLLNhanVien.TimNhanVien(tblDanhSach, TenNhanVien, ChucVu);
            txtThongBao.setEnabled(true);
            txtThongBao.setText("Có " + tblDanhSach.getRowCount() + " Nhân Viên Cần Tìm");
    }//GEN-LAST:event_cbbTimCVItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TimKiem;
    private javax.swing.ButtonGroup btgGioiTinh;
    private javax.swing.JButton btnChonHinh;
    private keeptoo.KButton btnDelete;
    private keeptoo.KButton btnEdit;
    private keeptoo.KButton btnNhapMoi;
    private keeptoo.KButton btnSave;
    private javax.swing.JComboBox<String> cbbMaChucVu;
    private javax.swing.JComboBox<String> cbbTimCV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblDiaChi1;
    private javax.swing.JLabel lblDiaChi2;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblMaCV;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSoCMND;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHinhAnh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtThongBao;
    private javax.swing.JTextField txtTimKiem;
    private com.toedter.calendar.JDateChooser txt_DateNgayVaoLam;
    private com.toedter.calendar.JDateChooser txt_DateSinh;
    // End of variables declaration//GEN-END:variables
}
