/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASM_TT_GUI;

import ASM_TT_BLL.BLLCombobox;
import ASM_TT_DAL.DALSanPham;
import ASM_TT_BLL.BllSanPham;
import ASM_TT_BLL.BLLNhanVien;
import ASM_TT_DAL.DALHangSx;
import ASM_TT_DAL.DalLoaiSp;
import ASM_TT_DTO.NhanVien;
import ASM_TT_DTO.SanPham;
import ASM_TT_HALPER.ChuyenDoi;
import ASM_TT_HALPER.ThongBao;
import ASM_TT_GUI.TabSanPham;
import ASM_TT_HALPER.HoTroNhapSo;
import ASM_TT_HALPER.Mycombobox;
import ASM_TT_HALPER.SetImage;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class TabSanPham extends javax.swing.JPanel {

    SetImage img = new SetImage();
    public static String sql = "SELECT * FROM SanPham";

    /**
     * Creates new form tabNhanVien
     */
    public TabSanPham() {
        initComponents();
        BllSanPham.LoadSanPham(tblDanhSach);
        ResultSet rsLSP = DalLoaiSp.GetAll();
        BLLCombobox.Load(cbbLoaiSP, rsLSP, true);
        ResultSet rsHSX = DALHangSx.GetAll();
        BLLCombobox.Load(CbbHangSX, rsHSX, true);
        ResultSet rsTimLoai = DALHangSx.GetAll();
        BLLCombobox.Load(cbbTimLoai, rsTimLoai, true);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtMaSP.setBackground(new Color(0, 0, 0, 0));
        txtTenSP.setBackground(new Color(0, 0, 0, 0));
        txtSoLuong.setBackground(new Color(0, 0, 0, 0));

        txtGiaNhap.setBackground(new Color(0, 0, 0, 0));
        txtTimKiem.setBackground(new Color(0, 0, 0, 0));
        txtMaSP.setEnabled(false);
    }
    int tam = 0;
    ImageIcon icon;
    String imageLocation = "bg.jpg";
    String imageName;

    public boolean kiemtraimg(String imagePath) {
        boolean kiemanh;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
            kiemanh = true;
        } catch (IOException e) {
            kiemanh = false;
        }
        return kiemanh;
    }

    public void setLabelImage(String imagePath) {
        if (imagePath == null) {
            imagePath = "d:\\pictures\\laptop\\default.jpg";
        }
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {

        }
        icon = new ImageIcon(img);

        lblHinhAnh.setIcon(icon);

    }

    public void setLabelImage(String imageLocation, String imageName) {
        if (imageName == null) {
            imageName = "default.jpg";
        }
        imageLocation = this.imageLocation;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imageLocation + imageName));
        } catch (IOException e) {
        }
        icon = new ImageIcon(img);

        lblHinhAnh.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        lblTenSP = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblHangSX = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblDVTinh = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        txt_Date = new com.toedter.calendar.JDateChooser();
        btnChonHinh = new javax.swing.JButton();
        lblHinhAnh = new javax.swing.JLabel();
        btnSave = new keeptoo.KButton();
        btnEdit = new keeptoo.KButton();
        btnDelete = new keeptoo.KButton();
        btnNhapMoi = new keeptoo.KButton();
        txtTimKiem = new javax.swing.JTextField();
        lblDVTinh1 = new javax.swing.JLabel();
        lblGia1 = new javax.swing.JLabel();
        txtGiaban = new javax.swing.JTextField();
        CbbHangSX = new javax.swing.JComboBox<>();
        lblDVTinh2 = new javax.swing.JLabel();
        cbbLoaiSP = new javax.swing.JComboBox<>();
        lblDVTinh3 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbbDonViTinh = new javax.swing.JComboBox<>();
        txtHinhAnh = new javax.swing.JTextField();
        cbbTimLoai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setOpaque(false);

        lblMaSP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaSP.setForeground(new java.awt.Color(0, 0, 153));
        lblMaSP.setText("Mã Sản Phẩm");

        txtMaSP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaSP.setForeground(new java.awt.Color(0, 0, 153));
        txtMaSP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        txtTenSP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenSP.setForeground(new java.awt.Color(0, 0, 153));
        txtTenSP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        lblTenSP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenSP.setForeground(new java.awt.Color(0, 0, 153));
        lblTenSP.setText("Tên Sản Phẩm");

        lblDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 0, 153));
        lblDate.setText("Ngày Nhập");

        lblHangSX.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHangSX.setForeground(new java.awt.Color(0, 0, 153));
        lblHangSX.setText("Hãng Sản Xuất");

        txtSoLuong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoLuong.setForeground(new java.awt.Color(0, 0, 153));
        txtSoLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtSoLuong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtSoLuongMouseMoved(evt);
            }
        });
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
        });

        lblDVTinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDVTinh.setForeground(new java.awt.Color(0, 0, 153));
        lblDVTinh.setText("Số Lượng");

        lblGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGia.setForeground(new java.awt.Color(0, 0, 153));
        lblGia.setText("Giá Nhập");

        txtGiaNhap.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtGiaNhap.setForeground(new java.awt.Color(0, 0, 153));
        txtGiaNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtGiaNhap.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtGiaNhapMouseMoved(evt);
            }
        });
        txtGiaNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiaNhapKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaNhapKeyReleased(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASM_TT_IMAGES/search.png"))); // NOI18N
        btnTim.setText(" Search");
        btnTim.setIconTextGap(5);
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        txt_Date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        txt_Date.setForeground(new java.awt.Color(0, 0, 153));
        txt_Date.setToolTipText("");
        txt_Date.setDateFormatString("dd-MM-yyyy");
        txt_Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnChonHinh.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnChonHinh.setText("Chọn Hình");
        btnChonHinh.setIconTextGap(5);
        btnChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHinhActionPerformed(evt);
            }
        });

        lblHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));

        btnSave.setBorder(null);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSave.setHideActionText(true);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setIconTextGap(45);
        btnSave.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnSave.setkBorderRadius(20);
        btnSave.setkEndColor(new java.awt.Color(144, 80, 202));
        btnSave.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnSave.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnSave.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnSave.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnSave.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnSave.setkStartColor(new java.awt.Color(37, 184, 253));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBorder(null);
        btnEdit.setText("Edit");
        btnEdit.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnEdit.setHideActionText(true);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setIconTextGap(45);
        btnEdit.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnEdit.setkBorderRadius(20);
        btnEdit.setkEndColor(new java.awt.Color(144, 80, 202));
        btnEdit.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnEdit.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnEdit.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnEdit.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnEdit.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnEdit.setkStartColor(new java.awt.Color(37, 184, 253));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBorder(null);
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnDelete.setHideActionText(true);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setIconTextGap(45);
        btnDelete.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnDelete.setkBorderRadius(20);
        btnDelete.setkEndColor(new java.awt.Color(144, 80, 202));
        btnDelete.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnDelete.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnDelete.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnDelete.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnDelete.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnDelete.setkStartColor(new java.awt.Color(37, 184, 253));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNhapMoi.setBorder(null);
        btnNhapMoi.setText("Refresh");
        btnNhapMoi.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnNhapMoi.setHideActionText(true);
        btnNhapMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapMoi.setIconTextGap(45);
        btnNhapMoi.setkBackGroundColor(new java.awt.Color(121, 213, 252));
        btnNhapMoi.setkBorderRadius(20);
        btnNhapMoi.setkEndColor(new java.awt.Color(144, 80, 202));
        btnNhapMoi.setkHoverEndColor(new java.awt.Color(121, 213, 252));
        btnNhapMoi.setkHoverForeGround(new java.awt.Color(67, 194, 203));
        btnNhapMoi.setkHoverStartColor(new java.awt.Color(246, 244, 193));
        btnNhapMoi.setkPressedColor(new java.awt.Color(229, 241, 251));
        btnNhapMoi.setkSelectedColor(new java.awt.Color(229, 241, 251));
        btnNhapMoi.setkStartColor(new java.awt.Color(37, 184, 253));
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        lblDVTinh1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDVTinh1.setForeground(new java.awt.Color(0, 0, 153));
        lblDVTinh1.setText("Đơn Vị Tính");

        lblGia1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGia1.setForeground(new java.awt.Color(0, 0, 153));
        lblGia1.setText("Giá Bán");

        txtGiaban.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtGiaban.setForeground(new java.awt.Color(0, 0, 153));
        txtGiaban.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));
        txtGiaban.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtGiabanMouseMoved(evt);
            }
        });
        txtGiaban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiabanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiabanKeyReleased(evt);
            }
        });

        CbbHangSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDVTinh2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDVTinh2.setForeground(new java.awt.Color(0, 0, 153));
        lblDVTinh2.setText("Loại Sản Phẩm");

        cbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDVTinh3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDVTinh3.setForeground(new java.awt.Color(0, 0, 153));
        lblDVTinh3.setText("Mô Tả");

        txtMoTa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMoTa.setForeground(new java.awt.Color(0, 0, 153));
        txtMoTa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        jButton1.setText("Thêm");

        jButton2.setText("Thêm HSX");

        cbbDonViTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cái", "Thanh", "Thùng" }));

        txtHinhAnh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHinhAnh.setForeground(new java.awt.Color(0, 0, 153));
        txtHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(113, 117, 204)));

        cbbTimLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDVTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDVTinh1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDVTinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(cbbDonViTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtGiaban))
                            .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CbbHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                        .addComponent(jButton2))
                                    .addComponent(txtGiaNhap)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDVTinh3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtMoTa))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbbTimLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChonHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtHinhAnh))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CbbHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDVTinh)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDVTinh1)
                            .addComponent(lblGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblHinhAnh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDVTinh2)
                            .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDVTinh3)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        tblDanhSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Vị Tính", "Giá nhập", "Giá bán", "Loại Sp", "Hãng Sản Xuất", "Ngày Nhập", "Mô tả", "Hình ảnh"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(7).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(7).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(11).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked

        int dongDuocChon = tblDanhSach.getSelectedRow();
        String MaNV = tblDanhSach.getValueAt(dongDuocChon, 1).toString();
        SanPham sp = BllSanPham.LaySanPhamTheoMa(MaNV);
        txtMaSP.setText(sp.getMaSanPham() + "");
        String image = (String) tblDanhSach.getValueAt(dongDuocChon, 11);

        txtTenSP.setText(sp.getTenSanPham());
        txtSoLuong.setText(ChuyenDoi.LaySoString(sp.getSoLuong()));
        cbbDonViTinh.setSelectedItem(sp.getDonViTinh());
        txtGiaNhap.setText(ChuyenDoi.LaySoString(sp.getGiaNhap()));
        txtGiaban.setText(ChuyenDoi.LaySoString(sp.getGiaBan()));
        cbbLoaiSP.setSelectedItem(sp.getMaLoaiSp());
        CbbHangSX.setSelectedItem(sp.getMaHangSx());
        txt_Date.setDate(sp.getNgayNhap());
        txtMoTa.setText(sp.getMoTa());
        txtHinhAnh.setText(image);
        img.setImageLabel(lblHinhAnh, "image//" + image);
        //Chuyển tab về đầu tiên
        lblHinhAnh.setText("");


    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHinhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("image");
        FileFilter filter = new FileNameExtensionFilter("Image file", "gjf", "jpg", "png");

        fileChooser.setFileFilter(filter);
        fileChooser.setMultiSelectionEnabled(false);

        int action = fileChooser.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            while (true) {
                if (!fileChooser.getSelectedFile().getName().matches("([^\\s]+(\\.(?i)(jpg|png|gif|bmp))$)")) {
                    JOptionPane.showMessageDialog(null, "Định dạng file hình đuôi phải là GIF, JPG, PNG !");
                    return;
                } else {
                    break;
                }
            }
            String imgFile = fileChooser.getSelectedFile().getName();
            txtHinhAnh.setText(imgFile);
            img.setImageLabel(lblHinhAnh, "image//" + imgFile);
        }
    }//GEN-LAST:event_btnChonHinhActionPerformed

    private void txtGiaNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaNhapKeyPressed
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtGiaNhapKeyPressed

    private void txtGiaNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaNhapKeyReleased
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtGiaNhapKeyReleased

    private void txtGiaNhapMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGiaNhapMouseMoved
        // TODO add your handling code here:
        txtGiaNhap.setToolTipText("Giá Tiền Phải Được Nhập Bằng Số .");
    }//GEN-LAST:event_txtGiaNhapMouseMoved

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (this.txtMaSP.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Mã Sản Phẩm Không Được Bỏ Trống");
        } else if (this.txtTenSP.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Tên Sản Phẩm Không Được Bỏ Trống");
        } else if (this.txtSoLuong.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Số Lượng Không Được Bỏ Trống");
        } else if (this.txtGiaNhap.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Giá Không Được Bỏ Trống");
        } else {
            int SoLuong;

            String TenSanPham = txtTenSP.getText();
            SoLuong = Integer.valueOf(txtSoLuong.getText());
            String DonViTinh = cbbDonViTinh.getSelectedItem().toString();
            double GiaNhap = ChuyenDoi.LaySoDouble(txtGiaNhap.getText());
            double GiaBan = ChuyenDoi.LaySoDouble(txtGiaban.getText());
            String MaLoaiSp;
            Mycombobox myCbb = (Mycombobox) cbbLoaiSP.getSelectedItem();
            MaLoaiSp = myCbb.maString();
            String HangSX;
            Mycombobox mycbb = (Mycombobox) CbbHangSX.getSelectedItem();
            HangSX = mycbb.maString();
            Date NgayNhap = txt_Date.getDate();
            String MoTa = txtMoTa.getText();
            String HinhAnh = txtHinhAnh.getText();
            SanPham sp = new SanPham(TenSanPham, SoLuong, DonViTinh,
                    GiaNhap, GiaBan, MaLoaiSp, HangSX, NgayNhap, MoTa, HinhAnh);
            ThongBao.ThongBaoDangNhap("Thông Báo", " Được Thêm Thành Công");
            BllSanPham.ThemSanPham(sp);
            BllSanPham.LoadSanPham(tblDanhSach);
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        if (this.txtMaSP.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Bạn Chưa Chọn Dòng Để Sửa !!");
        } else {
            
            String MaSP = txtMaSP.getText();
            int SoLuong;
            String TenSanPham = txtTenSP.getText();
            SoLuong = Integer.valueOf(txtSoLuong.getText());
            String DonViTinh = cbbDonViTinh.getSelectedItem().toString();
            double GiaNhap = ChuyenDoi.LaySoDouble(txtGiaNhap.getText());
            double GiaBan = ChuyenDoi.LaySoDouble(txtGiaban.getText());
            String MaLoaiSp;
            Mycombobox myCbb = (Mycombobox) cbbLoaiSP.getSelectedItem();
            MaLoaiSp = myCbb.maString();
            String HangSX;
            Mycombobox mycbb = (Mycombobox) CbbHangSX.getSelectedItem();
            HangSX = mycbb.maString();
            Date NgayNhap = txt_Date.getDate();
            String MoTa = txtMoTa.getText();
            String HinhAnh = txtHinhAnh.getText();

            SanPham sp = new SanPham(MaSP, TenSanPham, SoLuong, DonViTinh, GiaNhap,
                    GiaBan, MaLoaiSp, HangSX, NgayNhap, MoTa, HinhAnh);
            ThongBao.ThongBaoDangNhap("Thông Báo", " Đã Sửa Thành Công");
            BllSanPham.UpdateSanPham(sp);
            BllSanPham.LoadSanPham(tblDanhSach);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (this.txtMaSP.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, " Bạn Chưa Chọn Dòng Để Xoá !!");

        } else {
            int DSViTri[] = tblDanhSach.getSelectedRows();
            List<String> lstMaSP = new ArrayList<>();

            for (int i : DSViTri) {
                String MaNV = tblDanhSach.getValueAt(i, 1).toString();
                lstMaSP.add(MaNV);
            }

            BllSanPham.Delete(lstMaSP);

            BllSanPham.LoadSanPham(tblDanhSach);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        this.btnSave.setEnabled(true);
        this.txtMaSP.setText("");
        this.txtTenSP.setText("");
        this.txtSoLuong.setText("");
        this.txt_Date.getDate();
        //this.txtHangSanXuat.setText("");
        this.txtGiaNhap.setText("");
        this.txtTimKiem.setText("");


    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtSoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyPressed
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSoLuongKeyPressed

    private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyReleased
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSoLuongKeyReleased

    private void txtSoLuongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoLuongMouseMoved
        // TODO add your handling code here:
        txtSoLuong.setToolTipText("Giá Tiền Phải Được Nhập Bằng Số .");
    }//GEN-LAST:event_txtSoLuongMouseMoved

    private void txtGiabanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGiabanMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiabanMouseMoved

    private void txtGiabanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiabanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiabanKeyPressed

    private void txtGiabanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiabanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiabanKeyReleased

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String TenSp = "%" + txtTimKiem.getText()+"%";
        String MaLoaiSp;
        Mycombobox myCbb = (Mycombobox)cbbTimLoai.getSelectedItem();
        MaLoaiSp = myCbb.maString();
        
        BllSanPham.TimSanPham(tblDanhSach, TenSp, MaLoaiSp);
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String TenSp = "%" + txtTimKiem.getText()+"%";
        String MaLoaiSp;
        Mycombobox myCbb = (Mycombobox)cbbTimLoai.getSelectedItem();
        MaLoaiSp = myCbb.maString();
        
        BllSanPham.TimSanPham(tblDanhSach, TenSp, MaLoaiSp);
    }//GEN-LAST:event_txtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbHangSX;
    private javax.swing.JButton btnChonHinh;
    private keeptoo.KButton btnDelete;
    private keeptoo.KButton btnEdit;
    private keeptoo.KButton btnNhapMoi;
    private keeptoo.KButton btnSave;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbbDonViTinh;
    private javax.swing.JComboBox<String> cbbLoaiSP;
    private javax.swing.JComboBox<String> cbbTimLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDVTinh;
    private javax.swing.JLabel lblDVTinh1;
    private javax.swing.JLabel lblDVTinh2;
    private javax.swing.JLabel lblDVTinh3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGia1;
    private javax.swing.JLabel lblHangSX;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtGiaban;
    private javax.swing.JTextField txtHinhAnh;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    private com.toedter.calendar.JDateChooser txt_Date;
    // End of variables declaration//GEN-END:variables

}
